apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    components: mysql
    tier: backend
    environment: dev
  annotations:
    description: 
    jenkins: 
spec:
  containers:
  - name: nginx
    image: nginx